server:
    port: 8080
    servlet:
      session:
        cookie:
            http-only: false
            same-site: none
            secure: true

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/music_recommend_separation?useUnicode=true&characterEncoding=utf-8
        username: root
        password: llq12345

    security:
        user:
            roles:
                - user
                - common
                - admin
    mail:
        host: smtp.163.com
        username: 13097638440@163.com
        password: KTJAQMCUUGRZHFYO
        default-encoding: UTF-8
        properties:
            from: 13097638440@163.com

    data:
      redis:
        database: 0
        host: 127.0.0.1
        port: 6379
