server:
    port: 8080

spring:

    profiles:
      active: dev

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${db.mysql.host}:3306/music_recommend_separation?useUnicode=true&characterEncoding=utf-8
        username: 
        password: 

    security:
        user:
            roles:
                - user
                - common
                - admin
    mail:
        host: smtp.163.com
        username: 
        password: 
        default-encoding: UTF-8
        properties:
            from: 

    data:
      redis:
        database: 0
        host: ${db.redis.host}
        port: 6379

